#!/usr/bin/env python3
# -*- coding: utf-8 -*-
#
# License: BSD
#   https://raw.githubusercontent.com/stonier/py_trees_ros/devel/LICENSE
#
##############################################################################
# Documentation
##############################################################################
"""
Latched (TRANSIENT_LOCAL) version of ros2 topic echo for latched publishers.
"""
##############################################################################
# Imports
##############################################################################

import py_trees_ros.programs

##############################################################################
# Main
##############################################################################

if __name__ == '__main__':
    py_trees_ros.programs.latched_echo.main()
