#!/usr/bin/env python3
#
# License: BSD
#   https://raw.githubusercontent.com/stonier/py_trees_ros/devel/LICENSE
#
##############################################################################
# Documentation
##############################################################################
"""
Launch a qt dashboard for the tutorials.
"""
##############################################################################
# Imports
##############################################################################

import py_trees_ros
import rospy
import signal
import sys

from python_qt_binding.QtWidgets import QApplication, QMainWindow

##############################################################################
# Main
##############################################################################

if __name__ == '__main__':
    rospy.init_node('dashboard')
    app = QApplication(sys.argv)
    window = QMainWindow()
    dashboard = py_trees_ros.tutorials.qt.Dashboard()
    window.setCentralWidget(dashboard)
    window.show()
    signal.signal(signal.SIGINT, signal.SIG_DFL)
    sys.exit(app.exec_())
